spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.example.demo.mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

---

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/

feign:
  hystrix:
    enabled: true